server:
  port: 9527
spring:
  application:
    name: cloud-gatway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从服务在注册中心动态创建路由的功能
          lower-case-service-id: true #开启服务名称小写转换
      routes: # 可以配置多个路由
        - id: payment_routh # 路由id，没有固定规则但要求唯一
#          uri:  http://localhost:8001 # 匹配后提供服务的路由地址
          #lb://serverName是spring cloud  gatway在微服务中自动为我们创建的负载均衡uri
          uri:  lb://cloud-payment-service  # 匹配后提供服务的路由地址(默认情况下Gatway会根据注册中心注册的服务列表,  以注册中心上微服务名为路径创建动态路由进行转发,从而实现动态路由的功能)
          predicates:
            - Path=/payment/get/** # 路径相匹配的进行路由
            - After=2021-01-15T15:31:22.711+08:00[Asia/Shanghai]

        - id: payment_routh2 # 路由id，没有
#          uri:  http://localhost:8001 # 匹配后提供服务的路由地址
          #lb://serverName是spring cloud  gatway在微服务中自动为我们创建的负载均衡uri
          uri:  lb://cloud-payment-service  # 匹配后提供服务的路由地址(默认情况下Gatway会根据注册中心注册的服务列表,  以注册中心上微服务名为路径创建动态路由进行转发,从而实现动态路由的功能)
          predicates:
            - Path=/payment/lb # 路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka:  true
      fetch-registry:  true
      defaultZone: http://eureka7001.com:7001/eureka


