server:
  port: 7001

spring:
  application:
    name: cloud-eureka-service

eureka:
  instance:
#    hostname: localhost
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与 eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone:  http://localhost:7001/eureka/  #单机版
      defaultZone:  http://eureka7001.com:7001/eureka/  #单机
#      defaultZone:  http://eureka7002.com:7002/eureka/  #集群   互相注册,相互守望
#  server:
#    #关闭自我保护机制,保证不可用服务被及时剔除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000